spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
    output:
      ansi:
        enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    # open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    path: /
